version: '3.3'

services:
    prometheus:
        container_name: prometheus
        build: requirements/prometheus
        hostname: localhost
        volumes:
           - prometheus:/work_directory/prometheus
        networks:
           - app-network
        ports:
           - "9090:9090"
        restart: always
    # grafana:
    #     container_name: grafana
    #     build: requirements/grafana
    #     hostname: localhost
    #     volumes:
    #        - grafana:/tmp
    #     depends_on:
    #        - prometheus
    #     networks:
    #        - app-network
    #     ports:
    #        - "3000:3000"
    #     restart: always
    # server-1:
    #     container_name: server-1
    #     image: debian:buster
    #     hostname: localhost
    #     networks:
    #        - app-network
    #     depends_on:
    #        - prometheus
    #     restart: always

volumes:
    prometheus:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: ~/data/prometheus
    grafana:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: ~/data/grafana
networks:
    app-network:
        driver: bridge
