version: '3.3'

services:
    prometheus:
        container_name: prometheus
        build: requirements/prometheus
        hostname: localhost
        volumes:
           - prometheus:/work_directory/prometheus
        networks:
           - app-network
        ports:
           - "9090:9090"
        restart: always
    grafana:
        container_name: grafana
        build: requirements/grafana
        hostname: localhost
        volumes:
           - grafana:/work_directory
        depends_on:
           - prometheus
        networks:
           - app-network
        ports:
           - "3000:3000"
        restart: always
    server-1:
        container_name: server1
        build: requirements/server
        hostname: localhost
        networks:
           - app-network
        depends_on:
           - grafana
        restart: always

    server-2:
        container_name: server2
        build: requirements/server
        hostname: localhost
        networks:
           - app-network
        depends_on:
           - grafana
        restart: always

volumes:
    prometheus:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: ~/data/prometheus
    grafana:
         driver: local
         driver_opts:
            type: none
            o: bind
            device: ~/data/grafana
networks:
    app-network:
        driver: bridge
